---
title: "microclimalt"
date: today
date-format: medium
format: 
  gfm:
    toc: true
    toc-depth: 1
---

**microclimalt** is a project that aims to exploit the micrometeorological loggers installed by the ALT project in 2023 to improve our understanding of the horizontal, vertical and temporal variations in the microclimate of tropical forests.

> How do canopy openness, vegetation density and micropography (water and soil texture) affect topsoil, surface and aboveground air temperature, and topsoil moisture?

The objective are:

- Data gathering: microclimate ((HOBO), macroclimate (ERA5-Land & MeteoFrance), eddy flux (Guyaflux), vegetation structure (mulitple lidars, phenobs?), microtopography (lidar), and pedology
- Climate data temporal decomposition: using Fourrier Fast Transformation (e.g. <https://www.fortran.cnrs.fr/wp-content/uploads/2025/07/fortran-hingant.pdf>)
- Forest and microclimate offset computation
- Statistical exploration of horizontal and temporal drivers
- Simplified mechanistic modelling

## Project

**microclimalt** includes all codes to access the data (in `data/`) & analyse the data (`files.qmd`) with associated [documentation and figures](https://sylvainschmitt.github.io/microclim/). Intermediary files and outputs can be accessed in `outputs/`. The project takes advantage of `renv` to manage the R environment for enhanced reproducibility.

> To be reviewed later splitting raw and derived data.

## Core group

- Sylvain Schmitt CIRAD

- Erwan Hingant University of Picardie Jules Verne

- Jonathan Lenoir CNRS

- Vincyane Badouard ADEME

- Géraldine Derroire CIRAD

- Grégoire Vincent IRD

- Éric Marcon APT
